// <auto-generated />
using System;
using Kraken.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kraken.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KrakenDbContext))]
    partial class KrakenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Configuração da tabela Produto
            modelBuilder.Entity("Kraken.Core.Entities.Produto", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("NEWID()");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Produto");
            });

            // Configuração da tabela OrdemItem
            modelBuilder.Entity("Kraken.Core.Entities.OrdemItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("NEWID()");

                b.Property<Guid>("IdProduto")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Quantidade")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("IdProduto");

                b.ToTable("OrdemItem");
            });

            // Configuração de relacionamento entre OrdemItem e Produto
            modelBuilder.Entity("Kraken.Core.Entities.OrdemItem", b =>
            {
                b.HasOne("Kraken.Core.Entities.Produto", "Produto")
                    .WithMany()
                    .HasForeignKey("IdProduto")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Produto");
            });
#pragma warning restore 612, 618
        }
    }
}
